name: Deploy to PyPI 🚀

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'
    - name: Install build tools
      run: |
        pip install build
        pip install twine
        python -m build
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
        repository-url: https://upload.pypi.org/legacy/
